name: oc cli test

on:
  #pull_request:
  #  paths:
  #    - 'collections/**'
  #    - requirements.txt
  #    - bindep.txt
  #    - execution-environment.yml
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - 'collections/**'
  #    - requirements.txt
  #    - bindep.txt
  #    - execution-environment.yml

  # Schedule workflow run at 00:00 on Sunday
  #schedule:
  #  - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow:
    runs-on: ubuntu-latest
    #environment: deploy
    steps:
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4
        
      - name: Test oc
        id: octest
        run: oc version
